### ISSUE TITLE
CSS文本溢出显示省略号

### ISSUE THREAD

**Issue by sternzhang** [sternzhang/sternzhang.github.io#3]
````css
p {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2; // 规定可实现几行
    -webkit-box-orient: vertical;
}
````
#### text-overflow : clip | ellipsis 
+ clip : 　不显示省略标记（...），而是简单的裁切
+ ellipsis : 　当对象内文本溢出时显示省略标记（...）

#### -webkit-line-clamp
+ 用来限制在一个块元素显示的文本的行数。必须结合一下属性使用。

#### display: -webkit-box
+ 必须结合的属性 ，将对象作为弹性伸缩盒子模型显示 。 

#### -webkit-box-orient 
+ 必须结合的属性 ，设置或检索伸缩盒对象的子元素的排列方式 。
